### PR TITLE
Fix top margin of search result

### LINKED ISSUE #150: Modify search result margin
## Overview (Required)
According to the design, the margin size in the search result page is too small.

20180114_115643_asus z00ad

## Links
- https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a48b9e4032d092320fa2f44

### PR DESCRIPTION
**Pull request by ymegane**
## Issue
- close #150 

## Overview (Required)
Fix top margin of search result

## Links
- https://scene.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a48b9e6032d092320fa2fdd

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by konifar** [comment]
@ymegane Thanks! Your fix looks good.
but I thought it's enough to specify `paddingTop` and `clipToPadding="false"` to `RecyclerView` layout. What do you think?

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/item/SearchResultItemDecoration.kt [hunk 1]
```diff
@@ -0,0 +1,18 @@
+package io.github.droidkaigi.confsched2018.presentation.search.item
+
+import android.graphics.Rect
+import android.support.v7.widget.RecyclerView
+import android.view.View
+import io.github.droidkaigi.confsched2018.R
+
+class SearchResultItemDecoration : RecyclerView.ItemDecoration() {
+
+    override fun getItemOffsets(outRect: Rect, view: View, parent: RecyclerView, state: RecyclerView.State) {
```
Comment (droidkaigibot) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/item/SearchResultItemDecoration.kt]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/DroidKaigi/conference-app-2018/blob/f96a9b12d18c27c758efdfb6893fa3ac6ba817f0/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/item/SearchResultItemDecoration.kt#L10"></span>Exceeded max line length (100)</td>
    </tr>
  </tbody>
</table>

**Comment by ymegane** [comment]
@konifar Oh.., I agree 😅 
I'll change it 👍

File: app/src/main/res/values/dimens.xml [hunk 2]
```diff
@@ -10,6 +10,7 @@
 
     <!-- Search -->
     <dimen name="search_speaker_image_size">40dp</dimen>
+    <dimen name="search_result_top_margin">18dp</dimen>
```
Comment (konifar) [inline app/src/main/res/values/dimens.xml]: 🙋 
Why is this `18dp`? the item on the top has `6dp` margin?

Comment (ymegane) [reply app/src/main/res/values/dimens.xml]: Yes, The item has 6dp top and bottom margin.
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/res/layout/item_speech_session.xml

Comment (konifar) [reply app/src/main/res/values/dimens.xml]: Understood.
I think the item layout should not have `marginTop`...
But this layout is used in some places, so your fix seems enough.
I'll create another issue to remove `marginTop` in the item layout 👍 

Thanks!

**Comment by konifar** [comment]
LGTM!!

File: app/src/main/res/values/dimens.xml (hunk 2 above)
Comment (konifar) [reply app/src/main/res/values/dimens.xml]: Created the issue!
https://github.com/DroidKaigi/conference-app-2018/issues/172
