### PR TITLE
ClassNotFoundException occurs when the notification time is reached.

### LINKED ISSUE #456: [Assigned] ClassNotFoundException occurs when the notification time is reached.
## Overview (Required)

The reproduction procedure is as follows.

1. Launch droidkaigi2018 app. 
1-2. Enable Favorites for any sessions. (ex. DAY1 / 10:20-10:50)
1-3. Finish  droidkaigi2018 app. (back key)
2. Visit Settings app.
2-1. Data & time >  set to Feb 8, 2018 10:09 (GMT+09:00)
3. Reach at Feb 8, 2018 10:10 (GMT+09:00)
-> ClassNotFoundException occurs 

Also, it worked normally when testing with Debot.

I Tested Emulator(API27).

### Logcat 
```
02-08 21:52:33.599 1526-1582/? W/Intent: Failure filling in extras
                                         java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = io.github.droidkaigi.confsched2018.util.NotificationUtil$ChannelType)
                                             at android.os.Parcel.readSerializable(Parcel.java:3010)
                                             at android.os.Parcel.readValue(Parcel.java:2796)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:3114)
                                             at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:226)
                                             at android.os.Bundle.putAll(Bundle.java:288)
                                             at android.content.Intent.fillIn(Intent.java:9112)
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:264)
                                             at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:240)
                                             at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7726)
                                             at android.app.PendingIntent.send(PendingIntent.java:874)
                                             at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3122)
                                             at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2523)
                                             at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2646)
                                          Caused by: java.lang.ClassNotFoundException: io.github.droidkaigi.confsched2018.util.NotificationUtil$ChannelType
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:453)
                                             at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:629)
                                             at android.os.Parcel$2.resolveClass(Parcel.java:3001)
                                             at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1616)
                                             at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
                                             at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1729)
                                             at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
                                             at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374)
                                             at android.os.Parcel.readSerializable(Parcel.java:3004)
                                             at android.os.Parcel.readValue(Parcel.java:2796) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:3114) 
                                             at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:226) 
                                             at android.os.Bundle.putAll(Bundle.java:288) 
                                             at android.content.Intent.fillIn(Intent.java:9112) 
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:264) 
                                             at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:240) 
                                             at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7726) 
                                             at android.app.PendingIntent.send(PendingIntent.java:874) 
                                             at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3122) 
                                             at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2523) 
                                             at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2646) 
                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "io.github.droidkaigi.confsched2018.util.NotificationUtil$ChannelType" on path: DexPathList[[zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar", zip file "/system/framework/com.android.location.provider.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]
                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:453) 
                                             at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:629) 
                                             at android.os.Parcel$2.resolveClass(Parcel.java:3001) 
                                             at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1616) 
                                             at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521) 
                                             at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1729) 
                                             at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) 
                                             at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374) 
                                             at android.os.Parcel.readSerializable(Parcel.java:3004) 
                                             at android.os.Parcel.readValue(Parcel.java:2796) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:3114) 
                                             at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:226) 
                                             at android.os.Bundle.putAll(Bundle.java:288) 
                                             at android.content.Intent.fillIn(Intent.java:9112) 
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:264) 
                                             at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:240) 
                                             at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7726) 
                                             at android.app.PendingIntent.send(PendingIntent.java:874) 
                                             at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3122) 
                                             at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2523) 
                                             at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2646) 
02-08 21:52:34.218 12164-12164/? D/NotificationBroadcastReceiver: NotificationBroadcastReceiver.onReceive
02-08 21:52:34.218 12164-12164/? D/NotificationBroadcastReceiver: Show Notification
02-08 21:52:34.218 12164-12164/? D/AndroidRuntime: Shutting down VM
02-08 21:52:34.220 12164-12164/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: io.github.droidkaigi.confsched2018.debug, PID: 12164
                                                   java.lang.RuntimeException: Unable to start receiver io.github.droidkaigi.confsched2018.presentation.common.broadcastreceiver.NotificationBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type io.github.droidkaigi.confsched2018.util.NotificationUtil.ChannelType
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
                                                       at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                    Caused by: kotlin.TypeCastException: null cannot be cast to non-null type io.github.droidkaigi.confsched2018.util.NotificationUtil.ChannelType
                                                       at io.github.droidkaigi.confsched2018.presentation.common.broadcastreceiver.NotificationBroadcastReceiver.onReceive(NotificationBroadcastReceiver.kt:30)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
                                                       at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                       at android.os.Looper.loop(Looper.java:164) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

## Links
-

### PR DESCRIPTION
**Pull request by nukka123**
## Issue
- close #456 

## Overview (Required)
1. Remove ChannelType that was put on Intent
2. Change to notification helper class
3. showNotification move to helper class

## Links
-

## Screenshot
no screenshot.

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

File: app/src/main/java/io/github/droidkaigi/confsched2018/util/NotificationHelper.kt [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+        notificationManager.createNotificationChannel(channel)
+    }
+
+    fun showFavoriteSessionStart(
+            context: Context,
+            title: String,
+            text: String,
+            pendingIntent: PendingIntent?
+    ) {
+        val notification = NotificationCompat.Builder(context, ChannelType.FAVORITE_SESSION_START.id)
```
Comment (droidkaigibot) [inline app/src/main/java/io/github/droidkaigi/confsched2018/util/NotificationHelper.kt]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/DroidKaigi/conference-app-2018/blob/64ccc0d53bf9161070a08e30f2f4809bba0d6c3b/app/src/main/java/io/github/droidkaigi/confsched2018/util/NotificationHelper.kt#L53"></span>Exceeded max line length (100)</td>
    </tr>
  </tbody>
</table>

Comment (nukka123) [reply app/src/main/java/io/github/droidkaigi/confsched2018/util/NotificationHelper.kt]: oh..

**Comment by takahirom** [comment]
:eyes:

**Comment by takahirom** [comment]
I want to review this. But so sleepy

**Comment by takahirom** [comment]
If you have time ,Can you try this? 🙇 

```kotlin
sealed class ChannelNotification(
        open val title: String,
        open val text: String,
        val channelType: NotificationHelper.ChannelType
) {
    enum class NotificationType {
        FAVORITE_SESSION_START_NOTIFICATION
    }


    data class FavoriteSessionStart(
            override val title: String,
            override val text: String,
            val sessionId: String
    ) : ChannelNotification(
            title,
            text,
            NotificationHelper.ChannelType.FAVORITE_SESSION_START
    ) {
        override fun createPendingContentIntent(context: Context): PendingIntent {
            return TaskStackBuilder
                    .create(context)
                    .addNextIntent(MainActivity.createIntent(context))
                    .addNextIntent(SessionDetailActivity.createIntent(context, sessionId))
                    .getPendingIntent(
                            sessionId.hashCode(),
                            PendingIntent.FLAG_UPDATE_CURRENT
                    ) as PendingIntent
        }

        override fun putExtrasTo(intent: Intent) {
            intent.apply {
                putExtra(
                        EXTRA_NOTIFICATION_ID,
                        NotificationType.FAVORITE_SESSION_START_NOTIFICATION.ordinal
                )
                putExtra(EXTRA_SESSION_ID, sessionId)
                putExtra(EXTRA_TITLE, title)
                putExtra(EXTRA_TEXT, text)
            }
        }

        companion object {
            fun parse(intent: Intent): FavoriteSessionStart {
                return FavoriteSessionStart(
                        intent.getStringExtra(EXTRA_TITLE),
                        intent.getStringExtra(EXTRA_TEXT),
                        intent.getStringExtra(EXTRA_SESSION_ID)
                )
            }
        }
    }

    abstract fun putExtrasTo(intent: Intent)
    abstract fun createPendingContentIntent(context: Context): PendingIntent

    companion object {
        const val EXTRA_NOTIFICATION_ID = "EXTRA_NOTIFICATION_ID"
        private const val EXTRA_SESSION_ID = "EXTRA_SESSION_ID"
        private const val EXTRA_TITLE = "EXTRA_TITLE"
        private const val EXTRA_TEXT = "EXTRA_TEXT"

        fun parse(intent: Intent): ChannelNotification {
            return when (intent.getIntExtra(EXTRA_NOTIFICATION_ID, 0)) {
                NotificationType.FAVORITE_SESSION_START_NOTIFICATION.ordinal -> {
                    ChannelNotification.FavoriteSessionStart.parse(intent)
                }
                else -> throw NotImplementedError()
            }
        }
    }
}

object NotificationHelper {
    enum class ChannelType(
            val id: String,
            @StringRes val nameRes: Int,
            val importance: Int
    ) {
        FAVORITE_SESSION_START(
                "favorite_session_start_channel",
                R.string.notification_channel_name_start_favorite_session,
                NotificationManager.IMPORTANCE_HIGH
        );
    }


    fun initNotificationChannel(context: Context) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            ChannelType.values().forEach {
                createNotificationChannel(context, it)
            }
        }
    }

    @RequiresApi(Build.VERSION_CODES.O)
    private fun createNotificationChannel(context: Context, channelType: ChannelType) {
        val notificationManager =
                context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        val channelName = context.getString(channelType.nameRes)
        val channel = NotificationChannel(channelType.id, channelName, channelType.importance)
        notificationManager.createNotificationChannel(channel)
    }

    fun showNotification(
            context: Context,
            channelNotification: ChannelNotification
    ) {
        val notification =
                NotificationCompat.Builder(context, channelNotification.channelType.id)
                        .setContentTitle(channelNotification.title)
                        .setContentText(channelNotification.text)
                        .setFullScreenIntent(channelNotification.createPendingContentIntent(context), true)
                        .setAutoCancel(true)
                        .setColor(ContextCompat.getColor(context, R.color.primary))
                        .setSmallIcon(R.drawable.ic_notification).build()
        val notificationManagerCompat = NotificationManagerCompat.from(context)

        notificationManagerCompat.notify(channelNotification.text.hashCode(), notification)
    }
}
```

```kotlin
class NotificationBroadcastReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context?, intent: Intent?) {
        Timber.d("NotificationBroadcastReceiver.onReceive")
        if (!Prefs.enableNotification) {
            Timber.d("Do not show Notification")
            return
        }

        intent ?: return
        context ?: return
        val channelNotification = ChannelNotification.parse(intent)

        NotificationHelper.showNotification(
                context,
                channelNotification
        )
    }

    companion object {

        fun createIntent(
                context: Context,
                channelNotification: ChannelNotification
        ): Intent {
            return Intent(context, NotificationBroadcastReceiver::class.java).apply {
                channelNotification.putExtrasTo(this)

            }
        }
    }
}
```

**Comment by nukka123** [comment]
@takahirom 
Thank you for supplying the code!
The new class has changed its name.
How is it?

**Comment by takahirom** [comment]
How about this?
Probably we can move package codes presentation.common.notification
ChannelNotification -> ChannelNotification.kt
NotificationHelper -> NotificationHelper.kt
NotificationBroadcastReceiver -> NotificationBroadcastReceiver.kt

**Comment by takahirom** [comment]
Sorry I will check it's names 🙇

**Comment by takahirom** [comment]
`NotificationContent` sounds good 👍

**Comment by nukka123** [comment]
> move package codes presentation.common.notification
Good! 
"Notifications, as an important part of the Android user interface."
https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Design

**Comment by takahirom** [comment]
Thank you for refactoring👍 And thanks for letting me know. 🥇  LGTM 💯
