### PR TITLE
Fix timezone issue

### LINKED ISSUE #432: Session time incorrect when "Use local time" is enabled.
## Overview (Required)
The reproduction procedure is as follows.

1. Visit Settings app.
1-1. Data & time > Set Time zone to London. (GMT+00:00)
1-2. Perform CLEAR DATA of droidkaigi2018 app.
2. Launch droidkaigi2018 app. (Sessions will be displayed soon.)
3. droidkaigi2018’s Settings > "Use local time" to enable.
4. Back to AllSessions screen.
   (Session sequence is incorrect.)

step2 ("Use local time" is Disable) | step4 ("Use local time" is Enable)
------------ | -------------
pref_disable | pref_enable

This phenomenon seems to be related to the fact that toUnixMills () affects the following methods that generate objects.
* SessionWithSpeakers#toSession()
* SpecialSessions#getSessions()

Perhaps it may be necessary to reconsider the following tickets.
> Link Preference and behavior of settings that use local time #303

What is the thing application want to realize with ticket #303 ?

## Links
- #303
- #322

### PR DESCRIPTION
**Pull request by takahirom**
close #432
## Overview (Required)
- We should use JST all in the app. And only modify in showing.

### CODE REVIEW

**Comment by takahirom** [comment]
@nukka123 Can you review this?

**Comment by nukka123** [comment]
@takahirom 
Ok, just a moment.

**Comment by nukka123** [comment]
@takahirom
I was preparing for the question.
However, it seems that the answer has already been committed.

commited code is ok.
but, I think there is one problem.
When I operated it with my emulator, it seems that VIEW will not be updated when I return with Back key.

The problem has been corrected.
As # 303, I think either of the following is necessary.
* Take action to prompt update of VIEW
* Add a message urging the application to be restarted on the setting screen.

**Comment by takahirom** [comment]
Yes! I create will create that issue!

File: app/src/main/java/io/github/droidkaigi/confsched2018/util/ext/DateExt.kt [hunk 1]
```diff
@@ -1,11 +1,25 @@
...
+import io.github.droidkaigi.confsched2018.presentation.common.pref.Prefs
 import java.text.SimpleDateFormat
 import java.util.Date
 import java.util.Locale
+import java.util.TimeZone
 
 fun Date.toReadableDateTimeString() = "${toReadableDateString()} ${toReadableTimeString()}"
 
-fun Date.toReadableDateString() = SimpleDateFormat("MM/dd", Locale.getDefault()).format(this)
+fun Date.toReadableDateString() = SimpleDateFormat("MM/dd", Locale.US).apply {
```
Comment (konifar) [inline app/src/main/java/io/github/droidkaigi/confsched2018/util/ext/DateExt.kt]: 🙋‍♂️  How about changing this instance to static instance to avoid creating the instance every time?

Comment (konifar) [reply app/src/main/java/io/github/droidkaigi/confsched2018/util/ext/DateExt.kt]: Ah, sorry. This seems intentional according to this issue 📝 
https://github.com/DroidKaigi/conference-app-2018/pull/97

**Comment by konifar** [comment]
LGTM!

**Comment by nukka123** [comment]
LGTM😎
