### PR TITLE
Hide keyboard when forcus is out from query text field

### LINKED ISSUE #226: [Assigned] Hide keyboard when the tab change from search tab
## Overview (Required)
How to reproduce: 

1. Go to Search tab
2.. Search by text
3. Change tab

first

### PR DESCRIPTION
**Pull request by from-unknown**
## Issue
- close #226 

## Overview (Required)
- hide keyboard when user move to other tab
- hide keyboard when user move to other page

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt [hunk 1]
```diff
@@ -154,6 +155,12 @@ class SearchFragment : Fragment(), Injectable {
             }
         })
         changeSearchViewTextColor(searchView)
+
+        searchView.setOnQueryTextFocusChangeListener { view, b ->
```
Comment (takahirom) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt]: 📝

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt [hunk 2]
```diff
@@ -154,6 +155,12 @@ class SearchFragment : Fragment(), Injectable {
...
+            val imm = view.context.getSystemService(Context.INPUT_METHOD_SERVICE) as
```
Comment (konifar) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt]: 🙋 
`if (b) {` is unnecessary here?

Comment (from-unknown) [reply app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt]: @konifar Thank you for comment.
Actually without `if (!b) {`, this code seems working.
I checked stack trace and found that when pushed search button, `setImeVisibility(true)` ran after requesting focus.
In other words, IME is set to invisible then set to visible.
However, I think checking `!b` is better to do since no need to hide keyboard when query text field has focus and timing to set IME visible may change in future.
I'll add `if (!b) {` surround code which hiding IME.

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt [hunk 3]
```diff
@@ -154,6 +155,14 @@ class SearchFragment : Fragment(), Injectable {
             }
         })
         changeSearchViewTextColor(searchView)
+
+        searchView.setOnQueryTextFocusChangeListener { view, b ->
+            if(!b) {
```
Comment (droidkaigibot) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/DroidKaigi/conference-app-2018/blob/592267adb9a6421e5f5155eb59127e8436aaf4c6/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt#L160"></span>Missing spacing after “if”</td>
    </tr>
  </tbody>
</table>

Comment (from-unknown) [reply app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt]: I see, I'll fix it.

Comment (takahirom) [reply app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt]: Please use more meaningful good name instead of b 🙏

Comment (from-unknown) [reply app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt]: @takahirom aww you right, will change to `hasFocus`.

Comment (takahirom) [reply app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt]: Good name! 🙆‍♂️

**Comment by takahirom** [comment]
Looks good! Thank you for contributing 👍

**Comment by konifar** [comment]
LGTM! Thanks!

**Comment by from-unknown** [comment]
Your very welcome!
It was fun to try!
