### PR TITLE
Fix crash in Session Detail when Activity recreated

### LINKED ISSUE #542: [Assigned] Crash at Session Detail screen upon activity state loss
## Overview (Required)
Steps to reproduce:
- Navigate to any Session Detail screen.
- Put the app in background by tapping on device home button.
- Perform a bunch of other actions to put the device in low memory situation to trigger state loss.
- Open the app when you think you did enough.
- Crash.

Stacktrace:
`01-30 21:54:37.382 7569-7569/io.github.droidkaigi.confsched2018.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: io.github.droidkaigi.confsched2018.debug, PID: 7569
                                                                                        java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter speakers
                                                                                            at io.github.droidkaigi.confsched2018.presentation.common.view.SpeakersSummaryLayout.setSpeakers(SpeakersSummaryLayout.kt)
                                                                                            at io.github.droidkaigi.confsched2018.databinding.FragmentSessionDetailBinding.executeBindings(FragmentSessionDetailBinding.java:386)
                                                                                            at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:379)
                                                                                            at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:351)
                                                                                            at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:178)
                                                                                            at android.databinding.ViewDataBinding$5.onViewAttachedToWindow(ViewDataBinding.java:146)
                                                                                            at android.view.View.dispatchAttachedToWindow(View.java:15520)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

### PR DESCRIPTION
**Pull request by panpanini**
## Issue
- close #542

## Overview (Required)
- Allows null + quick return for speakers list
- attempts to simplify on click listener behavior 

I'm not sure if this is the right place to simplify the click listener, so I can remove it and create another PR if its better :bow:

### CODE REVIEW

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/view/SpeakersSummaryLayout.kt [hunk 1]
```diff
@@ -85,19 +87,16 @@ class SpeakersSummaryLayout @JvmOverloads constructor(
...
-
-            speakerAdapter.setOnItemClickListener(object : SpeakersAdapter.OnItemClickListener {
-                override fun onClick(view: View, speakerId: String) {
-                    if (speakerIdInDetail == null ||
-                            (speakerIdInDetail != null && !speakerIdInDetail.equals(speakerId))) {
-                        SpeakerDetailActivity.start(context, speakerId)
-                    }
-                }
-            })
+        if (speakerList.isEmpty()) return
```
Comment (takahirom) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/view/SpeakersSummaryLayout.kt]: 👍

**Comment by takahirom** [comment]
I think it is ok. Thanks 👍 LGTM 👍

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/view/SpeakersAdapter.kt [hunk 2]
```diff
@@ -13,19 +13,18 @@ import io.github.droidkaigi.confsched2018.model.Speaker
  */
 class SpeakersAdapter(var context: Context, var speakerList: List<Speaker>, val textColor: Int) :
         RecyclerView.Adapter<SpeakersAdapter.BindingHolder>() {
-    lateinit var listener: OnItemClickListener
+    var onSpeakerClick: (view: View, speakerId: String) -> Unit = { _,_ -> }
```
Comment (droidkaigibot) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/view/SpeakersAdapter.kt]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/DroidKaigi/conference-app-2018/blob/6a9a7cb43f2fabf424e12be273c6566fd676e6a1/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/view/SpeakersAdapter.kt#L16"></span>Missing spacing after “,”</td>
    </tr>
  </tbody>
</table>

Comment (takahirom) [reply app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/view/SpeakersAdapter.kt]: 🙏

**Comment by panpanini** [comment]
Done! sorry 🙏
