### PR TITLE
Fix Floating day view is weird in My Sessions page

### LINKED ISSUE #357: [Assigned] Floating day view is weird in My Sessions page
## Overview (Required)

20180120_185750_screenshot_2018-01-20-18-56-41 jpg 1080x1920

### PR DESCRIPTION
**Pull request by nappannda**
## Issue
- close #357 

## Overview (Required)
- Fix Floating day view is weird in My Sessions page

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/sessions/item/FavoriteSessionsSection.kt [hunk 1]
```diff
@@ -39,7 +37,7 @@ class FavoriteSessionsSection : Section() {
         var item = getItemOrNull(position) ?: return null
         item = item as? SpeechSessionItem ?: getItemOrNull(position + 1) ?: return null
         return when (item) {
-            is SpeechSessionItem -> {
+            is SessionItem -> {
```
Comment (takahirom) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/sessions/item/FavoriteSessionsSection.kt]: Nice catch 👍

**Comment by takahirom** [comment]
LGTM 😄
