### PR TITLE
fix feed item animation

### LINKED ISSUE #245: [Assigned] Feed screen title overlap when collapse
## Overview (Required)
- Title says everything

## Links
- Probably we can see Google I/O Implementation https://github.com/google/iosched/blob/e4364eec0d8f358215aee30cce2b4836ec169b5a/lib/src/main/java/com/google/samples/apps/iosched/feed/FeedViewHolder.java

### PR DESCRIPTION
**Pull request by sckm**
## Issue
- close #245 

## Overview (Required)
- This makes feed screen title don't overlap when collapse

## Links
- 

## Screenshot
I added dummy data because feed api  returns empty list.

Before | After
:--: | :--:
 |

### CODE REVIEW

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/feed/item/FeedItem.kt [hunk 1]
```diff
@@ -2,29 +2,44 @@ package io.github.droidkaigi.confsched2018.presentation.feed.item
...
+import android.support.transition.TransitionListenerAdapter
 import android.support.transition.TransitionManager
+import android.support.v7.widget.RecyclerView
+import android.view.View
 import com.xwray.groupie.databinding.BindableItem
 import io.github.droidkaigi.confsched2018.R
 import io.github.droidkaigi.confsched2018.databinding.ItemFeedBinding
 import io.github.droidkaigi.confsched2018.model.Post
 
+
```
Comment (droidkaigibot) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/feed/item/FeedItem.kt]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/DroidKaigi/conference-app-2018/blob/eafd3eb5ed00dd61554bb8b1ddd6dfcdf93d7135/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/feed/item/FeedItem.kt#L14"></span>Needless blank line(s)</td>
    </tr>
  </tbody>
</table>

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
So sorry, I deleted all Firestore feed items 🙇 
If you want to check, now I added items 👍

**Comment by takahirom** [comment]
Looks good 👍 
If you knew, could you tell me, which changes could you fix overlap? :raising_hand:

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/feed/item/FeedItem.kt [hunk 2]
```diff
@@ -2,29 +2,44 @@ package io.github.droidkaigi.confsched2018.presentation.feed.item
...
 ) : BindableItem<ItemFeedBinding>(
         post.hashCode().toLong()
 ) {
+    private val touchIgnorer = View.OnTouchListener { _, _ -> true }
 
     override fun bind(viewBinding: ItemFeedBinding, position: Int) {
         viewBinding.post = post
         viewBinding.root.setOnClickListener {
-            expanded = !expanded
             // FIXME: Animation!!
```
Comment (takahirom) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/feed/item/FeedItem.kt]: Now, can we remove this comment?👍

**Comment by sckm** [comment]
Passing RecyclerView to TransitionManager.beginDelayedTransition is important. 
If pass the ViewHolder root, other ViewHolder animation aren't occurred.

**Comment by takahirom** [comment]
I understood and I learned! Thanks 👍

**Comment by takahirom** [comment]
LGTM 👍 Thank you for smooth animation
