### PR TITLE
fix:Issue #402 We should use app intent rather than chrome custom tab.

### LINKED ISSUE #402: [Assigned] We should use app intent rather than chrome custom tab.
## Overview (Required)
- should use Intent instead of WebView

### PR DESCRIPTION
**Pull request by kiuchikeisuke**
## Issue
- close #402 

## Overview (Required)
- Tap header icon to open each Application. If a valid application is not installed, open it in default browser.

## Links
-

## Screenshot
Before | After
:--: | :--:
issue402_before | issue402_after

### CODE REVIEW

File: app/src/main/java/io/github/droidkaigi/confsched2018/presentation/about/AboutThisAppFragment.kt [hunk 1]
```diff
@@ -1,5 +1,8 @@
 package io.github.droidkaigi.confsched2018.presentation.about
 
+import android.content.Intent
+import android.content.pm.PackageManager
```
Comment (droidkaigibot) [inline app/src/main/java/io/github/droidkaigi/confsched2018/presentation/about/AboutThisAppFragment.kt]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/DroidKaigi/conference-app-2018/blob/0404ba7662fb7cce869b2997f0295ce884c1fd4e/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/about/AboutThisAppFragment.kt#L4"></span>Unused import</td>
    </tr>
  </tbody>
</table>

**Comment by takahirom** [comment]
:eyes:

**Comment by ycrack** [comment]
Wow... This is exactly what I envisioned... 💯

**Comment by takahirom** [comment]
Thanks 👍
Can you cherry-pick this?
I refactored this 👀 
 
* Use navigateToExternalBrowser for common use.
* Use host name for detecting facebook url
* When can not open intent specific app, The app use chrome custom tab

https://github.com/DroidKaigi/conference-app-2018/commit/4b2e95992817f07fcca614b68ddc46fc2657416e

**Comment by kiuchikeisuke** [comment]
Sorry for late, and thanks for refactoring!! :pray:

I cherry-pick and merge now! :smile:

**Comment by takahirom** [comment]
Thanks for checking intent behaviors and accepting refactoring👍
