### PR TITLE
Fix Firestore's offline get() problem

### LINKED ISSUE #277: [help wanted] Firestore will not return a response after a long time since you started using it.
## Overview (Required)
- We can not use favorite!! 😭 
- I can fix it clear app data. So probably, app internal problem.
- I can't fix this by force stop app.
- It occurred release and debug
- If it occurred, FavoriteFirestoreDatabase "Firestore:setupFavoritesDocument" is logged, But "Firestore:setupFavoritesDocument onComplete" is not logged.

https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt#L100

```kotlin
    @CheckResult
    private fun setupFavoritesDocument(currentUser: FirebaseUser): Single<FirebaseUser> {
        return Single.create({ e: SingleEmitter<FirebaseUser> ->
            if (DEBUG) Timber.d("Firestore:setupFavoritesDocument")
            val database = FirebaseFirestore.getInstance()
            val favorites = database.collection("users/" + currentUser.uid + "/favorites")
            favorites.get().addOnCompleteListener { task ->
                if (DEBUG) Timber.d("Firestore:setupFavoritesDocument onComplete")
```

### PR DESCRIPTION
**Pull request by kakajika**
## Issue
- close #277

## Overview (Required)
- When device is offline and document doesn't exist, Firestore's `get()` cause error and return nothing. Instead, I changed code to use `addSnapshotListener(...)`.
    - `FavoriteFirestoreDatabase::setupFavoritesDocument`
    - `FavoriteFirestoreDatabase::favorite`

## Links
- https://firebase.google.com/docs/firestore/manage-data/enable-offline#get_offline_data

### CODE REVIEW

File: app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt [hunk 1]
```diff
@@ -169,3 +178,8 @@ class FavoriteFirestoreDatabase : FavoriteDatabase {
         private const val DEBUG: Boolean = false
     }
 }
+
+fun <R> Task<R>.toSingle() = Single.create<R> { emitter ->
+    this.addOnSuccessListener { emitter.onSuccess(it) }
```
Comment (takahirom) [inline app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: 👍

File: app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt [hunk 2]
```diff
@@ -47,40 +47,39 @@ class FavoriteFirestoreDatabase : FavoriteDatabase {
...
-            })
+                }
+                e.setCancellable {
+                    if (DEBUG) Timber.d("Firestore:favorite dispose")
+                    listener.remove()
+                }
+
+            // To avoid get -> write -> get -> ... loop, split task.
+            }).flatMap<Boolean> { documentSnapshot ->
+                val nowFavorite = documentSnapshot.exists() && (documentSnapshot.data[session.id] == true)
```
Comment (droidkaigibot) [inline app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/DroidKaigi/conference-app-2018/blob/95b031d4253971596641ef60b22cf6d265f33487/app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt#L69"></span>Exceeded max line length (100)</td>
    </tr>
  </tbody>
</table>

File: app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt (hunk 1 above)
Comment (kakajika) [reply app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: Sorry, I don't know where to put the extension, so put in same file.

Comment (takahirom) [reply app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: If you think this extension method is useful for other files, Please put it FirebaseTaskExt.kt in util.ext package

Comment (kakajika) [reply app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: Thanks! I'll do it.

File: app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt [hunk 3]
```diff
@@ -47,40 +47,39 @@ class FavoriteFirestoreDatabase : FavoriteDatabase {
         Single.error(NotPreparedException())
     } else {
         getCurrentUser().flatMap { currentUser ->
-            return@flatMap Single.create<Boolean>({ e ->
+            return@flatMap Single.create<DocumentSnapshot>({ e ->
```
Comment (takahirom) [inline app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: Can we commonize getting the favorite Single object by creating method?

Comment (kakajika) [reply app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: Well... a method like `getFavorite(currentUser, sessionId)` ?

Comment (takahirom) [reply app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: I think like this private fun getFavoritesDocument(current):Single<DocumentSnapshot>
And, I think it is better to use this method not only `favorite()` but also `setupFavoritesDocument()`
But, This is not required!
We can merge this 👍

Comment (kakajika) [reply app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: `favorite()` requires `"users/${currentUser.uid}/favorites/${session.id}"` (Document),
on the other hand,
 `setupFavoritesDocument()` requires `"users/${currentUser.uid}/favorites"` (Collection).

So, it seems to be difficult to commonize them. 🤔

Comment (takahirom) [reply app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt]: Thanks 👍  I understood!

**Comment by takahirom** [comment]
Looks good 👍 Thank you for your suggestion!
We are so helped 🙇
